// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
  repository: url: "https://kubevirt.github.io/kubevirt"
  chart: name: "kubevirt"
  sync: targetNamespace: "kubevirt-system"
  helmValues: {}
}
