// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
  repository: url: "oci://docker.io/envoyproxy"
  chart: name: "gateway-helm"
  sync: targetNamespace: "envoy-gateway-system"
  helmValues: {}
}
