// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
  repository: url: "https://metallb.github.io/metallb"
  chart: name: "metallb"
  sync: targetNamespace: "metallb-system"
  helmValues: {}
}
