// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
  repository: url: "https://helm.cilium.io/"
  chart: name: "cilium"
  sync: targetNamespace: "kube-system"
  helmValues: {
    operator: replicas: 1
    ipam: mode:         "kubernetes"
    hubble: {
      relay: enabled: true
      ui: enabled: true
    }
    envoy: enabled: true
  }
}
